---

- name: install depences
  apt: pkg={{ item }}
  with_items:
    - pdns-server
    - pdns-backend-mysql

- name: copy PowerDNS config file
  template:
    src=etc/powerdns/pdns.conf.j2
    dest=/etc/powerdns/pdns.conf
    mode=0600
  notify: reload powerdns

- name: copy PowerDNS mysql config file
  template:
    src=etc/powerdns/pdns.d/pdns.local.gmysql.conf.j2
    dest=/etc/powerdns/pdns.d/pdns.local.gmysql.conf
    mode=0600
  notify: reload powerdns

- name: disable bind config
  file:
    dest=/etc/powerdns/pdns.d/pdns.simplebind.conf
    state=absent
  notify: reload powerdns

