---

- name: install depences
  apt: pkg={{ item }}
  with_items:
    - pdns-server
    - pdns-backend-mysql

- name: copy PowerDNS config file
  template:
    src=etc/powerdns/pdns.conf.j2
    dest=/etc/powerdns/pdns.conf
    mode=0600
  notify: reload powerdns

- name: disable DNSSEC
  lineinfile:
    dest=/etc/powerdns/pdns.d/pdns.local.gmysql
    regexp=^gmysql-dnssec=
    line=gmysql-dnssec=no
  notify: reload powerdns

