---
- name: install depences
  apt: pkg={{ item }}
  with_items:
    - bind9
    - daemontools

- name: copy bind9 config file
  copy:
    src=etc/bind/named.conf.options
    dest=/etc/bind/named.conf.options
  notify: reload bind9

- name: make zones directory
  file:
    path=/var/cache/bind/slave
    state=directory
    owner=bind

- name: copy zone_sync.sh
  template:
    src=home/dnsops/zone_sync/zone_sync.sh.j2
    dest=/home/{{ opsuser }}/zone_sync/zone_sync.sh
    owner={{ opsuser }}
    mode=0755

- name: add zone_sync.sh to cron
  cron:
    name="zone_sync.sh"
    user="root"
    job="setlock -n /tmp/zone_sync.lock /home/{{ opsuser }}/zone_sync/zone_sync.sh"
